version: 2.1

parameters:
  run:
    type: boolean
    default: false

commands:
  ping_service:
    steps:
      - run:
          name: Ping service
          command: |
            if [[ -z "$WHATSON_API_URL" ]]; then
              echo "Error: WHATSON_API_URL environment variable is not set."
              exit 1
            fi

            echo "Calling: $WHATSON_API_URL"

            if ! curl -sf "$WHATSON_API_URL" > /dev/null; then
              echo "Error: Failed to reach $WHATSON_API_URL"
              exit 1
            fi

            echo "Service ping successful."
  setup_env:
    steps:
      - checkout
      - run:
          name: Install npm globally
          command: sudo npm install -g npm@9.8.0
      - run:
          name: Install dependencies
          command: npm install
  run_tests:
    steps:
      - run:
          name: Run tests
          command: npm run test-remote
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/

jobs:
  build:
    docker:
      - image: cimg/node:20.5.1
    environment:
      NODE_OPTIONS: "--max-old-space-size=8192"
    steps:
      - ping_service
      - setup_env
      - run_tests

workflows:
  build:
    when: << pipeline.parameters.run >>
    jobs:
      - build
